[project]
name = "crypto-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "debugpy>=1.8.13",
    "dotenv>=0.9.9",
    "telethon>=1.39.0",
]
